name: Test Environment and Secrets

on: 
  workflow_dispatch:  # Trigger this workflow manually

jobs:
  test_env:
    runs-on: ubuntu-latest
    env:
        DEPLOY_URL: ${{ vars.DEPLOY_URL }}
    steps:
      - name: Display Environment Variables
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"  # Example secret
          echo "MY_CUSTOM_ENV_VAR: ${{ env.MY_CUSTOM_ENV_VAR }}" 
          env | grep 'DEPLOY_'  # View environment variables starting with 'DEPLOY_'
          echo "DEPLOY_URL : $DEPLOY_URL"

