name: Test Environment and Secrets

on: 
  workflow_dispatch:  # Trigger this workflow manually
env:
  env_var: "develop"
jobs:
  test_env:
    runs-on: ubuntu-latest
    env:
        DEPLOY_URL: ${{ vars.DEPLOY_URL }}
    steps:
      - name: Display Environment Variables
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"  # Example secret
          echo "DEPLOY_URL : $DEPLOY_URL, ${{ vars.DEPLOY_URL }}"

