name: Test Environment and Secrets

on: 
  workflow_dispatch:  # Trigger this workflow manually

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
      - name: Display Environment Variables
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"  # Example secret
          echo "DEPLOY_URL : $DEPLOY_URL, : ${{ vars.DEPLOY_URL }} : ${{ env.DEPLOY_URL }} : ${{ secrets.DEPLOY_URL }} : $TEST_VARS"
       
